locale:
  path: /
  defaults:  { _controller: PageBundle:Default:locale }
  
page_start:
    pattern:  /{_locale}/start
    defaults: { _controller: PageBundle:Default:start }  

page_o_nas:
    pattern:  /{_locale}/about
    defaults: { _controller: PageBundle:Default:o_nas }
    
page_oferta:
    pattern:  /{_locale}/offer
    defaults: { _controller: PageBundle:Default:oferta }
    
page_serwis:
    pattern:  /{_locale}/service
    defaults: { _controller: PageBundle:Default:serwis }
    
page_opancerzenie:
    pattern:  /{_locale}/armoring
    defaults: { _controller: PageBundle:Default:opancerzenie }      

page_faq:
    pattern:  /{_locale}/faq
    defaults: { _controller: PageBundle:Default:faq }  
    
page_kontakt:
    pattern:  /{_locale}/contact
    defaults: { _controller: PageBundle:Default:kontakt } 
    methods: [GET]
    
page_kontakt_send:
    pattern:  /{_locale}/contact
    defaults: { _controller: PageBundle:Default:kontaktSend } 
    methods: [POST]    

catalog_brand_select:
    pattern:  /{_locale}/catalog
    defaults: { _controller: PageBundle:Catalog:brandSelect }     

catalog_model_select:
    pattern: /{_locale}/catalog/brand/{brandId}
    defaults: { _controller: PageBundle:Catalog:modelSelect } 
    
catalog_partsgroup_select:
    pattern: /{_locale}/catalog/model/{modelId}
    defaults: { _controller: PageBundle:Catalog:partsGroupSelect }    
    
catalog_part_select:
    pattern: /{_locale}/catalog/partsgroup/{partsGroupId}
    defaults: { _controller: PageBundle:Catalog:partSelect }   

catalog_my_cart:
    pattern: /{_locale}/cart
    defaults: { _controller: PageBundle:Catalog:myCart }  

ajax_add_part_to_cart:
    pattern:  /{_locale}/cart/add_part/{partId}
    defaults: { _controller: PageBundle:Catalog:ajaxAddPartToCart }
    