parameters:
    exchange_rates.class: ExoticCarParts\ModelsBundle\Service\ExchangeRates
    cart.class: ExoticCarParts\ModelsBundle\Service\Cart

services:
    exchange_rates:
        class: %exchange_rates.class%
    cart:
        class: %cart.class%
        arguments: [@doctrine.orm.entity_manager, @session]