parameters:
#    page.example.class: ExoticCarParts\PageBundle\Example

services:
#    page.example:
#        class: %page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
