models:
    resource: "@ModelsBundle/Resources/config/routing.yml"
    prefix:   /

crawler:
    resource: "@CrawlerBundle/Resources/config/routing.yml"
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /


