parameters:
    ricambia_crawler.class: ExoticCarParts\CrawlerBundle\Service\RicambiaCrawler

services:
    ricambia_crawler:
        class: %ricambia_crawler.class%
        arguments: [ "@doctrine.orm.entity_manager" ]

