parameters:
#    crawler.example.class: ExoticCarParts\CrawlerBundle\Example

services:
#    crawler.example:
#        class: %crawler.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
